### ISSUE TITLE
Interpolation problems on tight turns

### ISSUE THREAD

**Issue by goamberg** [remisalmon/gpx_interpolate#6] opened 2020-06-17 21:23 UTC
I had problems on a file, did some testing and figured out that the problems appear on the section with the tight ~180° turn (green)
![image](https://user-images.githubusercontent.com/26245753/84950865-cfe84700-b0ef-11ea-883b-edb8787fee2e.png)
Here are the 2 gpx tracks for blue and green
[10.zip](https://github.com/remisalmon/gpx_interpolate/files/4795132/10.zip)

While the blue track has no problem to interpolate, the green one gives some errors.
I tested it on about 4-5 turns from this file and its repeatable.

(It is not an issue for myself, but as I spent 3 hours looking why my file isnt working, maybe its helpful to you or others ;-) )

**Comment by remisalmon** [comment] 2020-06-18 05:13
This is caused by duplicate trackpoints at the same location, fixed in the last commit.

**Closed as completed** 2020-06-18 05:12 UTC
